### PR TITLE
Home section

### PR DESCRIPTION
**Pull request by yassin282**

### CODE REVIEW

**Comment by Amahmoud1994** [comment]
Fix your conflicts first

**Comment by yassin282** [comment]
@kadyEG review and merge

**Comment by abdelrahman-elkady** [comment]
ok again , what is this cute [style.css](www.github.com/sapphireworks/website-generator/blob/10e342cac2667dcb8d70d786b98217d031934ede/style.css) on the root of the project ?

**Comment by abdelrahman-elkady** [comment]
still there check
- `/style.css`
- `app/assets/stylesheets/style.css`

are these really needed ?

**Pull request merged**
